/**
 * THE STUDIO'S OWN WIKI CONTENT.
 *
 * Round: Wiki Redesign Phase 4, Sep 2026.
 *
 * WHAT THIS IS FOR
 * ----------------
 * "This needs to be editable and customizable by the admins and be able to be
 * added to." Two different asks live inside that sentence, and conflating them
 * is how a content model goes wrong:
 *
 *   an OVERLAY  sits on top of something the app already ships — a machine, an
 *               Academy topic, a quick card. "At Westlake we set this one two
 *               notches lower than the card says."
 *   a PAGE      is a subject the shipped corpus does not cover at all. "How we
 *               run a first session", "Front desk phone script".
 *
 * ONE COLLECTION, DISCRIMINATED BY `kind`
 * ---------------------------------------
 * `studios/{studioId}/wiki/{docId}`, and both shapes live in it. The
 * alternative — `wikiOverlays` and `wikiPages` — means two rules blocks, two
 * listeners, two editors and two search paths for what is, from the reader's
 * side, the same thing: words this studio wrote. It also means the next
 * content type is a third of everything.
 *
 * The cost of one collection is that the rule has to branch on `kind`, and
 * that branch is load-bearing:
 *
 *   overlays  ANY trainer may write. Same posture as machineNotes — an
 *             overlay carries no override power over safety content, and the
 *             person who discovers that the left pad sticks is the person on
 *             the floor. This is also the half AJ meant by "whatever knowledge
 *             trainers end up providing".
 *   pages     studio leaders and above. A new page is a claim about how the
 *             studio operates, which is a management act.
 *
 * `kind` is pinned on update in the rule, so an overlay cannot be flipped into
 * a page to escape the leader check.
 *
 * THE SHIPPED CORPUS IS NEVER TOUCHED
 * -----------------------------------
 * Nothing here edits `features/academy/content/*.json`. Those 283,000 words
 * are generated by scripts/build-academy-content.ts from the Academy's own
 * documents, and they are the same at every location — a studio "correcting"
 * them would silently fork the curriculum. An overlay renders BESIDE the
 * baseline, attributed and dated, and the baseline is always still there.
 * That is also why nothing here can go wrong in a way that loses source
 * material: the worst case is a studio note nobody wanted.
 *
 * PURE MODULE — no Firestore, no React. See useStudioWiki / studio-wiki-mutations.
 */

export type WikiDocKind = "page" | "overlay";

/**
 * What an overlay can attach to.
 *
 * These are the addressable things in the two wikis. `machine` is a Catalog
 * machine id; the rest are Academy content ids from the generated corpus.
 */
export type WikiTargetType =
  | "machine"
  | "topic"
  | "card"
  | "script"
  | "overview";

export type WikiBlockKind = "heading" | "bullet" | "para";

export interface WikiBlock {
  kind: WikiBlockKind;
  text: string;
}

/** Where a page is filed on the Academy index. */
export type WikiPageSection = "method" | "equipment" | "operations" | "other";

export const PAGE_SECTIONS: WikiPageSection[] = [
  "method",
  "equipment",
  "operations",
  "other",
];

export const PAGE_SECTION_LABEL: Record<WikiPageSection, string> = {
  method: "How we coach",
  equipment: "Equipment",
  operations: "Running the floor",
  other: "Everything else",
};

/** studios/{studioId}/wiki/{docId} */
export interface StudioWikiDoc {
  id: string;
  studioId: string;
  kind: WikiDocKind;

  title: string;
  /** One line under the title. Optional — a short overlay needs no summary. */
  summary?: string;
  blocks: WikiBlock[];

  /** Overlays only. Together these form the document id — see targetDocId. */
  targetType?: WikiTargetType;
  targetId?: string;

  /** Pages only. */
  section?: WikiPageSection;

  /** Machines this applies to. Makes a page findable from a machine article. */
  machineIds: string[];
  tags: string[];

  authorId: string;
  authorName: string;
  createdAt?: unknown;
  updatedAt?: unknown;
  updatedBy?: string;
  updatedByName?: string;

  /**
   * Retired, not deleted — same call the playbook makes. A machine article may
   * be linking to it and history is not ours to erase.
   */
  retiredAt?: unknown;
  retiredBy?: string;
}

export interface StudioWikiDraft {
  kind: WikiDocKind;
  title: string;
  summary?: string;
  /** The raw editor text. Parsed to blocks at the door — see parseBlocks. */
  body: string;
  targetType?: WikiTargetType;
  targetId?: string;
  section?: WikiPageSection;
  machineIds?: string[];
  tags?: string[];
}

export const WIKI_TITLE_MAX = 160;
export const WIKI_SUMMARY_MAX = 300;
export const WIKI_BODY_MAX = 12000;
/** Enough for a long procedure; short of "somebody pasted the whole manual". */
export const WIKI_BLOCK_MAX = 400;

/* ------------------------------------------------------------------ *
 * Document ids
 * ------------------------------------------------------------------ */

/**
 * Firestore document ids may not contain `/` and may not be `.` or `..`.
 * Machine and topic ids are already slugs, but a studio-authored machine id
 * has been through a text field at some point, so it is sanitised rather than
 * trusted.
 */
function slug(value: string): string {
  return (
    value
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 120) || "unknown"
  );
}

/**
 * ONE OVERLAY PER TARGET, and the id says so.
 *
 * A deterministic id rather than a random one, for the same reason the
 * per-trainer submission document uses the trainer id: two trainers editing
 * the Chest Press overlay at once should collide on one document and see each
 * other's text, not silently create two overlays that both render and
 * contradict each other. "Add a section" is a block inside this document, not
 * a second document.
 */
export function targetDocId(type: WikiTargetType, id: string): string {
  return `${type}__${slug(id)}`;
}

export function isOverlayFor(
  doc: StudioWikiDoc,
  type: WikiTargetType,
  id: string,
): boolean {
  return (
    doc.kind === "overlay" && doc.targetType === type && doc.targetId === id
  );
}

/* ------------------------------------------------------------------ *
 * Blocks
 * ------------------------------------------------------------------ */

/**
 * Editor text -> blocks.
 *
 * The editor is a plain textarea, deliberately. A rich text editor is weeks of
 * work, a serialisation format to maintain forever, and a paste surface that
 * smuggles in styling from Word; a trainer standing at a machine on an iPad
 * wants to type three lines. So the format is the two conventions everybody
 * already knows from chat apps:
 *
 *     ## Heading
 *     - bullet
 *     anything else is a paragraph
 *
 * Blank lines separate blocks and are dropped. Nothing is ever lost by this
 * parse — serialiseBlocks is its exact inverse, so an admin who saves and
 * re-opens sees what they typed.
 */
export function parseBlocks(body: string): WikiBlock[] {
  const out: WikiBlock[] = [];
  for (const raw of body.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line) continue;
    if (line.startsWith("##")) {
      const text = line.replace(/^#+\s*/, "").trim();
      if (text) out.push({ kind: "heading", text: text.slice(0, WIKI_BLOCK_MAX) });
      continue;
    }
    // "•" as well as "-" and "*": iPadOS autocorrect turns a leading hyphen
    // into a bullet character in some keyboards, and a trainer who typed a
    // list should get a list.
    if (/^[-*•]\s+/.test(line)) {
      const text = line.replace(/^[-*•]\s+/, "").trim();
      if (text) out.push({ kind: "bullet", text: text.slice(0, WIKI_BLOCK_MAX) });
      continue;
    }
    out.push({ kind: "para", text: line.slice(0, WIKI_BLOCK_MAX) });
  }
  return out;
}

/** Blocks -> editor text. The exact inverse of parseBlocks. */
export function serialiseBlocks(blocks: WikiBlock[]): string {
  return blocks
    .map((b) => {
      if (b.kind === "heading") return `## ${b.text}`;
      if (b.kind === "bullet") return `- ${b.text}`;
      return b.text;
    })
    .join("\n");
}

/** Roughly how long this takes to read. Shown the way the Academy shows it. */
export function readingMinutes(blocks: WikiBlock[]): number {
  const words = blocks.reduce((n, b) => n + b.text.split(/\s+/).length, 0);
  return Math.max(1, Math.round(words / 220));
}

/* ------------------------------------------------------------------ *
 * Validation
 * ------------------------------------------------------------------ */

export interface WikiDraftProblem {
  field: "title" | "body" | "section";
  message: string;
}

/**
 * What must be true before a save is attempted.
 *
 * Gentle minimums, per the standing rule on this project: required fields stay
 * required because a wiki full of empty pages is worse than no wiki, but there
 * is no aggressive character count. A three-word answer that is correct beats
 * a padded one that clears a threshold.
 */
export function validateDraft(draft: StudioWikiDraft): WikiDraftProblem[] {
  const problems: WikiDraftProblem[] = [];
  const title = draft.title.trim();
  const blocks = parseBlocks(draft.body);

  if (title.length < 3) {
    problems.push({ field: "title", message: "Give it a title someone could search for." });
  }
  if (title.length > WIKI_TITLE_MAX) {
    problems.push({ field: "title", message: `Titles are capped at ${WIKI_TITLE_MAX} characters.` });
  }
  if (blocks.length === 0) {
    problems.push({ field: "body", message: "Write something — even one line." });
  }
  if (draft.body.length > WIKI_BODY_MAX) {
    problems.push({ field: "body", message: "That is longer than a wiki page should be. Split it into two." });
  }
  if (draft.kind === "page" && !draft.section) {
    problems.push({ field: "section", message: "Pick a section so it can be found." });
  }
  return problems;
}

/* ------------------------------------------------------------------ *
 * Finding things again
 * ------------------------------------------------------------------ */

export interface StudioWikiHit {
  doc: StudioWikiDoc;
  score: number;
}

/**
 * Rank studio docs against a term.
 *
 * Deliberately naive substring matching over weighted fields, no index and no
 * service — the same call searchPlaybook makes and for the same reason: a
 * studio's own wiki is tens of documents, not thousands, and a search service
 * here would be infrastructure to maintain in exchange for nothing a trainer
 * could perceive. Revisit past a few hundred docs.
 *
 * Every word has to land somewhere, or "shoulder press" returns everything
 * that merely says "shoulder".
 */
export function searchStudioWiki(
  docs: StudioWikiDoc[],
  term: string,
  opts: { kind?: WikiDocKind; machineId?: string; includeRetired?: boolean } = {},
): StudioWikiHit[] {
  const words = term.trim().toLowerCase().split(/\s+/).filter(Boolean);
  const hits: StudioWikiHit[] = [];

  for (const doc of docs) {
    if (doc.retiredAt && !opts.includeRetired) continue;
    if (opts.kind && doc.kind !== opts.kind) continue;
    if (opts.machineId) {
      const attached =
        doc.machineIds.includes(opts.machineId) ||
        isOverlayFor(doc, "machine", opts.machineId);
      if (!attached) continue;
    }

    let score = 0;
    if (words.length === 0) {
      score = 1;
    } else {
      const title = doc.title.toLowerCase();
      const tags = doc.tags.join(" ").toLowerCase();
      const body = `${doc.summary ?? ""} ${doc.blocks.map((b) => b.text).join(" ")}`.toLowerCase();
      let missing = false;
      for (const w of words) {
        const inTitle = title.includes(w);
        const inTags = tags.includes(w);
        const inBody = body.includes(w);
        if (!inTitle && !inTags && !inBody) {
          missing = true;
          break;
        }
        if (inTitle) score += 6;
        if (inTags) score += 4;
        if (inBody) score += 1;
      }
      if (missing) continue;
    }

    hits.push({ doc, score });
  }

  return hits.sort(
    (a, b) => b.score - a.score || a.doc.title.localeCompare(b.doc.title),
  );
}

/* ------------------------------------------------------------------ *
 * Attribution
 * ------------------------------------------------------------------ */

/**
 * "Updated 12 Sep 2026" from whatever the timestamp field actually holds.
 *
 * Duck-typed rather than importing Firestore's Timestamp, which keeps this
 * module pure and testable. The value can legitimately be four different
 * things: a Timestamp from a snapshot, a Date, an ISO string from an older
 * write, or — for the moment between an optimistic render and the server's
 * answer — `null`, because `serverTimestamp()` resolves to null locally.
 *
 * Returns "" rather than a placeholder for the unknown cases. An attribution
 * line reading "Updated Invalid Date" is worse than one with no date.
 */
export function whenLabel(value: unknown): string {
  let date: Date | null = null;

  if (value instanceof Date) {
    date = value;
  } else if (typeof value === "string" || typeof value === "number") {
    const d = new Date(value);
    if (!Number.isNaN(d.getTime())) date = d;
  } else if (
    value &&
    typeof value === "object" &&
    typeof (value as { toDate?: unknown }).toDate === "function"
  ) {
    try {
      const d = (value as { toDate: () => Date }).toDate();
      if (d instanceof Date && !Number.isNaN(d.getTime())) date = d;
    } catch {
      date = null;
    }
  }

  if (!date) return "";
  return date.toLocaleDateString(undefined, {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}

/** Live pages for one section, newest title order. Retired ones excluded. */
export function pagesInSection(
  docs: StudioWikiDoc[],
  section: WikiPageSection,
): StudioWikiDoc[] {
  return docs
    .filter((d) => d.kind === "page" && !d.retiredAt && d.section === section)
    .sort((a, b) => a.title.localeCompare(b.title));
}
