import { describe, expect, it } from "vitest";
import cardsFile from "./content/cards.json";
import scriptsFile from "./content/scripts.json";
import overviewsFile from "./content/overviews.json";
import {
  buildAcademyMachines,
  buildAliasIndex,
  cardTitle,
  machineName,
  scriptTitle,
  whatItHas,
} from "./academy-machines";
import type { CardsFile, OverviewsFile, ScriptsFile } from "./types";

/**
 * Run against the REAL corpus, not fixtures.
 *
 * The join this module performs is only as good as the data it is joining, and
 * the data is regenerated by scripts/build-academy-content.ts. A fixture test
 * would keep passing while a rebuild quietly broke every deep-dive link on the
 * Academy index. These assertions fail loudly instead.
 */

const cards = (cardsFile as unknown as CardsFile).cards;
const scripts = (scriptsFile as unknown as ScriptsFile).scripts;
const overviews = (overviewsFile as unknown as OverviewsFile).overviews;

describe("the corpus itself", () => {
  it("still has cards, scripts and overviews", () => {
    expect(cards.length).toBeGreaterThan(0);
    expect(scripts.length).toBeGreaterThan(0);
    expect(overviews.length).toBeGreaterThan(0);
  });

  /*
   * The reason this module exists. Ten of the eighteen card titles are the
   * Academy's abbreviations rather than names ("CP", "Pd", "LC"), so anything
   * rendering card.title verbatim shows a row called "Pd".
   */
  it("still has card titles that are abbreviations, not names", () => {
    const abbreviated = cards.filter((c) => cardTitle(c).length <= 6);
    expect(abbreviated.length).toBeGreaterThan(0);
  });
});

describe("machineName", () => {
  it("gives the app's canonical name, not the Academy's", () => {
    expect(machineName("m-chest-fly")).toBe("Pec Fly");
    expect(machineName("m-pulldown")).toBe("Torso Arm");
    expect(machineName("m-lumbar")).toBe("Low Back");
  });

  /*
   * m-neck is contested between two database entries. CANONICAL_TO_DB_KEY
   * resolves it to cervical_extension — the one whose safety copy says NEVER
   * take to failure. If this ever returns "4-Way Neck", the Academy has
   * started showing the weaker warning.
   */
  it("resolves the contested neck id to the Cervical Extension", () => {
    expect(machineName("m-neck")).toBe("Cervical Extension");
  });

  it("returns null rather than guessing for an unknown id", () => {
    expect(machineName("m-not-a-machine")).toBeNull();
  });
});

describe("cardTitle / scriptTitle", () => {
  it("strips the Quick Reference Guide suffix", () => {
    expect(
      cardTitle({ title: "Seated Dip - Quick Reference Guide" } as never),
    ).toBe("Seated Dip");
  });

  it("takes the machine off the head of a script summary", () => {
    expect(
      scriptTitle({
        summary: "Leg Curl - Gap 3 for most – starts at LT, chest up",
        abbr: "LC",
      } as never),
    ).toBe("Leg Curl");
  });

  it("falls back to the abbreviation when a script has no summary", () => {
    expect(scriptTitle({ abbr: "LC" } as never)).toBe("LC");
  });
});

describe("buildAliasIndex", () => {
  const alias = buildAliasIndex(cards, scripts);

  it("knows a machine by the app's name, the Academy's name and the code", () => {
    expect(alias.get("pecfly")).toBe("m-chest-fly");
    expect(alias.get("chestflye")).toBe("m-chest-fly");
    expect(alias.get("cf")).toBe("m-chest-fly");
  });

  /* The only route to the "Triceps Extension" deep dive: the app calls it
     "Seated Tricep" and the script's head is just "Triceps". */
  it("knows a machine by its database key", () => {
    expect(alias.get("tricepsextension")).toBe("m-tricep-ext");
  });
});

describe("buildAcademyMachines", () => {
  const rows = buildAcademyMachines(cards, scripts, overviews);

  it("collapses three lists into one row per machine", () => {
    expect(rows.length).toBe(20);
    expect(new Set(rows.map((r) => r.machineId)).size).toBe(rows.length);
  });

  it("never shows an abbreviation as a name", () => {
    const abbrs = new Set(cards.map((c) => c.abbr.toLowerCase()));
    for (const row of rows) {
      expect(abbrs.has(row.name.toLowerCase())).toBe(false);
      expect(row.name.length).toBeGreaterThan(3);
    }
  });

  it("is alphabetical by the app's name", () => {
    const names = rows.map((r) => r.name);
    expect(names).toEqual([...names].sort((a, b) => a.localeCompare(b)));
  });

  /*
   * The number that matters. Every overview is a machine write-up, so every
   * one should reach a machine — if a corpus rebuild drops this, deep-dive
   * links silently disappear from the index.
   */
  it("attaches every deep dive to a machine", () => {
    const attached = rows.filter((r) => r.overviewId).length;
    expect(attached).toBe(overviews.length);
  });

  it("attaches each overview to at most one machine", () => {
    const used = rows.map((r) => r.overviewId).filter(Boolean);
    expect(new Set(used).size).toBe(used.length);
  });

  it("keeps the two machines that have a script but no card", () => {
    const scriptOnly = rows.filter((r) => !r.cardId && r.scriptId);
    expect(scriptOnly.map((r) => r.machineId).sort()).toEqual([
      "m-lateral-raise",
      "m-tricep-ext",
    ]);
  });

  it("carries the Academy's abbreviation for every carded machine", () => {
    for (const row of rows) {
      if (row.cardId) expect(row.abbr).toBeTruthy();
    }
  });

  it("survives content that has not loaded yet", () => {
    expect(buildAcademyMachines(null, null, null)).toEqual([]);
    expect(buildAcademyMachines(cards, null, null).length).toBe(cards.length);
  });
});

describe("whatItHas", () => {
  it("lists only what exists", () => {
    expect(
      whatItHas({
        machineId: "m-x",
        name: "X",
        abbr: "X1",
        cardId: "c",
        scriptId: null,
        overviewId: "o",
        workout: null,
      }),
    ).toBe("X1 · Card · Deep dive");
  });

  it("omits the code when the corpus has none", () => {
    expect(
      whatItHas({
        machineId: "m-x",
        name: "X",
        abbr: null,
        cardId: null,
        scriptId: "s",
        overviewId: null,
        workout: null,
      }),
    ).toBe("Script");
  });
});
