/**
 * MSF TOPICS — the Academy, readable from the app.
 *
 * Round: MSF Topics, Sep 2026.
 *
 * `docs/msf-academy/` has been in the repo carrying 283,000 words of the
 * studio's own methodology, and its README closed with the whole problem:
 * "Nothing reads these files at runtime." A trainer who wanted to know what
 * the Academy says about turnarounds had to have Drive access and know which
 * of 214 files to open.
 *
 * FOUR WAYS IN, BECAUSE THERE ARE FOUR REASONS TO COME HERE
 * --------------------------------------------------------
 *   Learn      the numbered curriculum, in teaching order, read end to end
 *   At the machine  the 18 quick reference cards, one per machine
 *   Look it up      the glossary, because the Academy insists on exact terms
 *   Go deep         the 19 full equipment write-ups
 *
 * These are genuinely different jobs. A trainer mid-shift wanting the seat
 * position for the Leg Press is not going to read a module on progressive
 * overload, and folding both into one list of 80 topics would serve neither.
 *
 * The content is generated by scripts/build-academy-content.ts and loaded a
 * module at a time — see useAcademyContent.ts for why the loaders are written
 * out longhand.
 */

import React, { useMemo, useState } from "react";
import {
  ArrowLeft,
  BookOpen,
  ClipboardList,
  GraduationCap,
  Layers,
  MessageSquareQuote,
  Search,
  Type,
} from "lucide-react";
import {
  ACADEMY_INDEX,
  useAcademyCards,
  useAcademyCues,
  useAcademyGlossary,
  useAcademyModule,
  useAcademyOverviews,
  useAcademyScripts,
  useTopicSearch,
} from "./useAcademyContent";
import type { Block, MachineScript, QuickCard } from "./types";
import "./academy.css";

type Tab = "learn" | "cueing" | "cards" | "glossary" | "deep";

const TABS: { id: Tab; label: string; icon: React.ReactNode }[] = [
  { id: "learn", label: "Curriculum", icon: <GraduationCap className="w-4 h-4" /> },
  { id: "cueing", label: "Cueing", icon: <MessageSquareQuote className="w-4 h-4" /> },
  { id: "cards", label: "At the machine", icon: <ClipboardList className="w-4 h-4" /> },
  { id: "glossary", label: "Glossary", icon: <Type className="w-4 h-4" /> },
  { id: "deep", label: "Deep dives", icon: <Layers className="w-4 h-4" /> },
];

export interface AcademyViewProps {
  /** Open straight onto this machine's card. Set when arriving from a machine. */
  initialMachineId?: string | null;
  onBack?: () => void;
}

export function AcademyView({ initialMachineId, onBack }: AcademyViewProps) {
  const [tab, setTab] = useState<Tab>(initialMachineId ? "cards" : "learn");
  const [moduleId, setModuleId] = useState<string | null>(null);
  const [topicId, setTopicId] = useState<string | null>(null);
  const [cardId, setCardId] = useState<string | null>(null);
  const [overviewId, setOverviewId] = useState<string | null>(null);
  const [search, setSearch] = useState("");

  const { content, loading, failed } = useAcademyModule(moduleId);
  const cards = useAcademyCards(tab === "cards" || Boolean(initialMachineId));
  const cues = useAcademyCues(tab === "cueing");
  /*
   * The scripts load for the cueing tab AND whenever we arrived from a
   * machine, because for the Lateral Raise and the Triceps Extension the
   * script is the ONLY instruction the corpus carries — there is no quick
   * reference card for either.
   */
  const scripts = useAcademyScripts(tab === "cueing" || Boolean(initialMachineId));
  const [scriptId, setScriptId] = useState<string | null>(null);
  const glossary = useAcademyGlossary(tab === "glossary");
  const overviews = useAcademyOverviews(tab === "deep");
  const runSearch = useTopicSearch();
  const hits = useMemo(() => runSearch(search), [runSearch, search]);

  /** Arriving from a machine opens that machine's card, not the list. */
  const openCard = useMemo(() => {
    if (cardId) return cards?.find((c) => c.id === cardId) ?? null;
    if (initialMachineId) {
      return cards?.find((c) => c.machineId === initialMachineId) ?? null;
    }
    return null;
  }, [cards, cardId, initialMachineId]);

  const openTopic = content?.topics.find((t) => t.id === topicId) ?? null;
  const openOverview = overviews?.find((o) => o.id === overviewId) ?? null;
  const openScript = scripts?.find((s) => s.id === scriptId) ?? null;
  /** The script for the machine we arrived from, if it has one. */
  const machineScript = initialMachineId
    ? (scripts?.find((s) => s.machineId === initialMachineId) ?? null)
    : null;

  /* ── a topic, open ───────────────────────────────────────────────── */
  if (openTopic) {
    return (
      <Reader
        title={openTopic.title}
        eyebrow={openTopic.moduleLabel ?? content?.title}
        meta={`${openTopic.readingMinutes} min read`}
        blocks={openTopic.blocks}
        source={openTopic.source}
        onBack={() => setTopicId(null)}
      />
    );
  }

  if (openOverview) {
    return (
      <Reader
        title={openOverview.title}
        eyebrow="Comprehensive equipment overview"
        meta={`${openOverview.readingMinutes} min read`}
        blocks={openOverview.blocks}
        onBack={() => setOverviewId(null)}
      />
    );
  }

  if (openScript) {
    return <ScriptReader script={openScript} onBack={() => setScriptId(null)} />;
  }

  if (openCard) {
    return (
      <CardReader
        card={openCard}
        script={machineScript}
        onOpenScript={machineScript ? () => setScriptId(machineScript.id) : undefined}
        onBack={() => {
          setCardId(null);
          onBack?.();
        }}
      />
    );
  }

  /*
   * Arrived from a machine that has no card. Two machines are in this
   * position — the Lateral Raise and the Triceps Extension — and both have a
   * full script, so going straight to it beats showing an empty list.
   */
  if (initialMachineId && machineScript && !openCard) {
    return <ScriptReader script={machineScript} onBack={() => onBack?.()} />;
  }

  /* ── a module's topic list ───────────────────────────────────────── */
  if (moduleId) {
    const mod = ACADEMY_INDEX.modules.find((m) => m.id === moduleId);
    return (
      <div className="acd">
        <button type="button" className="acd__back" onClick={() => setModuleId(null)}>
          <ArrowLeft className="w-3.5 h-3.5" />
          All topics
        </button>
        <h1 className="acd__title">{mod?.title}</h1>
        <p className="acd__blurb">{mod?.blurb}</p>

        {failed ? (
          <p className="acd__empty">
            This module could not be loaded. Check your connection and try again.
          </p>
        ) : loading || !content ? (
          <p className="acd__empty">Loading…</p>
        ) : (
          <ol className="acd__list">
            {content.topics.map((t, i) => (
              <li key={t.id}>
                <button type="button" className="acd__row" onClick={() => setTopicId(t.id)}>
                  <span className="acd__n">{i + 1}</span>
                  <span className="acd__rowmain">
                    <span className="acd__rowtitle">{t.title}</span>
                    <span className="acd__rowmeta">{t.readingMinutes} min</span>
                  </span>
                </button>
              </li>
            ))}
          </ol>
        )}
      </div>
    );
  }

  /* ── the landing ─────────────────────────────────────────────────── */
  return (
    <div className="acd">
      <header className="acd__head">
        <h1 className="acd__title">
          <BookOpen className="w-5 h-5" aria-hidden />
          MSF Topics
        </h1>
        <p className="acd__blurb">
          The Academy, in the app. {ACADEMY_INDEX.modules.length} modules,{" "}
          {ACADEMY_INDEX.modules.reduce((n, m) => n + m.topics.length, 0)} topics,{" "}
          {ACADEMY_INDEX.cardCount} machine cards.
        </p>
      </header>

      <div className="acd__searchwrap">
        <Search className="w-4 h-4 acd__searchicon" aria-hidden />
        <input
          type="search"
          className="acd__search"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Search topics…"
          aria-label="Search topics"
        />
      </div>

      {search.trim() && (
        <div className="acd__hits">
          {hits.length === 0 ? (
            <p className="acd__empty">Nothing matches “{search.trim()}”.</p>
          ) : (
            hits.map((h) => (
              <button
                key={`${h.moduleId}-${h.topicId}`}
                type="button"
                className="acd__hit"
                onClick={() => {
                  setSearch("");
                  setModuleId(h.moduleId);
                  setTopicId(h.topicId);
                }}
              >
                <span className="acd__hittitle">{h.title}</span>
                <span className="acd__hitmod">{h.moduleTitle}</span>
              </button>
            ))
          )}
        </div>
      )}

      <div className="acd__tabs" role="tablist">
        {TABS.map((t) => (
          <button
            key={t.id}
            type="button"
            role="tab"
            aria-selected={tab === t.id}
            className="acd__tab"
            onClick={() => setTab(t.id)}
          >
            {t.icon}
            {t.label}
          </button>
        ))}
      </div>

      {tab === "learn" && (
        <ol className="acd__modules">
          {ACADEMY_INDEX.modules.map((m) => (
            <li key={m.id}>
              <button type="button" className="acd__module" onClick={() => setModuleId(m.id)}>
                <span className="acd__modn">{m.n}</span>
                <span className="acd__modmain">
                  <span className="acd__modtitle">{m.title}</span>
                  <span className="acd__modblurb">{m.blurb}</span>
                  <span className="acd__modmeta">
                    {m.topics.length} topic{m.topics.length === 1 ? "" : "s"} ·{" "}
                    {m.topics.reduce((n, t) => n + t.readingMinutes, 0)} min
                  </span>
                </span>
              </button>
            </li>
          ))}
        </ol>
      )}

      {tab === "cueing" && (
        <>
          <p className="acd__note">
            What to say, and when. The phrases are grouped by the moment in the
            set they belong to; the scripts below are the full spoken
            instruction for one machine, start to finish.
          </p>
          {!cues ? (
            <p className="acd__empty">Loading…</p>
          ) : (
            <div className="acd__cues">
              {cues.map((m) => (
                <section key={m.moment} className="acd__moment">
                  <h2>{m.moment}</h2>
                  {m.notes.map((n, i) => (
                    <p key={i} className="acd__cuenote">
                      {n}
                    </p>
                  ))}
                  <ul className="acd__phrases">
                    {m.phrases.map((ph, i) => (
                      <li key={i}>{ph}</li>
                    ))}
                  </ul>
                </section>
              ))}
            </div>
          )}

          <h2 className="acd__subhead">Full scripts, by machine</h2>
          {!scripts ? (
            <p className="acd__empty">Loading…</p>
          ) : (
            <div className="acd__cards">
              {scripts.map((sc) => (
                <button
                  key={sc.id}
                  type="button"
                  className="acd__card"
                  onClick={() => setScriptId(sc.id)}
                >
                  <span className="acd__cardabbr">{sc.abbr}</span>
                  <span className="acd__cardtitle">
                    {sc.summary?.split(/\s[-–]\s/)[0] ?? sc.abbr}
                    <em className="acd__cardsub">{sc.workout}</em>
                  </span>
                </button>
              ))}
            </div>
          )}
        </>
      )}

      {tab === "cards" && (
        <>
          <p className="acd__note">
            One card per machine, written to be read standing at it. Every card
            says it is the abbreviated version — the deep dives tab has the full
            write-up.
          </p>
          {!cards ? (
            <p className="acd__empty">Loading…</p>
          ) : (
            <div className="acd__cards">
              {cards.map((c) => (
                <button
                  key={c.id}
                  type="button"
                  className="acd__card"
                  onClick={() => setCardId(c.id)}
                >
                  <span className="acd__cardabbr">{c.abbr}</span>
                  <span className="acd__cardtitle">
                    {c.title.replace(/\s*[-–]\s*Quick Reference Guide\s*$/i, "")}
                  </span>
                </button>
              ))}
            </div>
          )}
        </>
      )}

      {tab === "glossary" && (
        <>
          <p className="acd__note">
            The Academy is explicit that these exact terms are the ones to use.
          </p>
          {!glossary ? (
            <p className="acd__empty">Loading…</p>
          ) : (
            <dl className="acd__glossary">
              {glossary.map((e) => (
                <React.Fragment key={e.term}>
                  <dt>{e.term}</dt>
                  <dd>{e.definition}</dd>
                </React.Fragment>
              ))}
            </dl>
          )}
        </>
      )}

      {tab === "deep" && (
        <>
          <p className="acd__note">
            The full write-up for each machine — everything a practitioner is
            expected to hold before training anyone on it.
          </p>
          {!overviews ? (
            <p className="acd__empty">Loading…</p>
          ) : (
            <ol className="acd__list">
              {overviews.map((o) => (
                <li key={o.id}>
                  <button type="button" className="acd__row" onClick={() => setOverviewId(o.id)}>
                    <span className="acd__rowmain">
                      <span className="acd__rowtitle">{o.title}</span>
                      <span className="acd__rowmeta">{o.readingMinutes} min</span>
                    </span>
                  </button>
                </li>
              ))}
            </ol>
          )}
        </>
      )}
    </div>
  );
}

/* ------------------------------------------------------------------ *
 * READERS
 * ------------------------------------------------------------------ */

function Reader({
  title,
  eyebrow,
  meta,
  blocks,
  source,
  onBack,
}: {
  title: string;
  eyebrow?: string;
  meta?: string;
  blocks: Block[];
  source?: string;
  onBack: () => void;
}) {
  return (
    <article className="acd acd--reader">
      <button type="button" className="acd__back" onClick={onBack}>
        <ArrowLeft className="w-3.5 h-3.5" />
        Back
      </button>
      {eyebrow && <p className="acd__eyebrow">{eyebrow}</p>}
      <h1 className="acd__title">{title}</h1>
      {meta && <p className="acd__meta">{meta}</p>}

      <div className="acd__prose">
        {blocks.map((b, i) => {
          if (b.kind === "heading") return <h2 key={i}>{b.text}</h2>;
          if (b.kind === "subheading") return <h3 key={i}>{b.text}</h3>;
          if (b.kind === "bullet") {
            return (
              <p key={i} className="acd__bullet">
                {b.text}
              </p>
            );
          }
          return <p key={i}>{b.text}</p>;
        })}
      </div>

      {source && (
        <p className="acd__source">
          Source: <code>{source}</code>
        </p>
      )}
    </article>
  );
}

function CardReader({
  card,
  script,
  onOpenScript,
  onBack,
}: {
  card: QuickCard;
  script?: MachineScript | null;
  onOpenScript?: () => void;
  onBack: () => void;
}) {
  return (
    <article className="acd acd--reader">
      <button type="button" className="acd__back" onClick={onBack}>
        <ArrowLeft className="w-3.5 h-3.5" />
        Back
      </button>
      <p className="acd__eyebrow">Quick reference</p>
      <h1 className="acd__title">
        {card.title.replace(/\s*[-–]\s*Quick Reference Guide\s*$/i, "")}
      </h1>

      {onOpenScript && script && (
        <button type="button" className="acd__scriptlink" onClick={onOpenScript}>
          <MessageSquareQuote className="w-4 h-4" aria-hidden />
          <span>
            <strong>Full spoken script</strong>
            <em>Word for word, setup through the last rep</em>
          </span>
        </button>
      )}

      {card.sections.map((s) => (
        <section key={s.heading} className="acd__section">
          <h2>{s.heading}</h2>
          <ul>
            {s.items.map((it, i) => (
              <li key={i}>{it}</li>
            ))}
          </ul>
        </section>
      ))}
    </article>
  );
}

/**
 * A machine's script.
 *
 * The distinction the layout carries is the one the source makes: a quoted
 * line is what the trainer SAYS, everything else is what they do or watch
 * for. Rendering both as plain paragraphs would lose it, and a trainer
 * rehearsing needs to know which words are theirs.
 */
function ScriptReader({
  script,
  onBack,
}: {
  script: MachineScript;
  onBack: () => void;
}) {
  return (
    <article className="acd acd--reader">
      <button type="button" className="acd__back" onClick={onBack}>
        <ArrowLeft className="w-3.5 h-3.5" />
        Back
      </button>
      <p className="acd__eyebrow">{script.workout} · spoken script</p>
      <h1 className="acd__title">{script.summary ?? script.abbr}</h1>
      <p className="acd__meta">
        Lines in <span className="acd__saidkey">quotes and colour</span> are said
        out loud.
      </p>

      {script.beats.map((b) => (
        <section key={b.beat} className="acd__section">
          <h2>{b.beat}</h2>
          <div className="acd__script">
            {b.lines.map((l, i) =>
              l.spoken ? (
                <p key={i} className="acd__said">
                  {l.text}
                </p>
              ) : (
                <p key={i} className="acd__do">
                  {l.text}
                </p>
              ),
            )}
          </div>
        </section>
      ))}
    </article>
  );
}
